# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: CI

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [15.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    name: Build and Test

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup Node.js
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Decrypt secrets
      run: |
        cd secrets;
        gpg --quiet --batch --yes --decrypt --passphrase="$SECRET_PASSPHRASE" \
        --output firebase_config.tar firebase_config.tar.gpg
        tar xvf firebase_config.tar
        gpg --quiet --batch --yes --decrypt --passphrase="$SECRET_PASSPHRASE" \
        --output firestore_key.tar firestore_key.tar.gpg
        tar xvf firestore_key.tar
        gpg --quiet --batch --yes --decrypt --passphrase="$SECRET_PASSPHRASE" \
        --output secret_key.tar secret_key.tar.gpg
        tar xvf secret_key.tar
        gpg --quiet --batch --yes --decrypt --passphrase="$SECRET_PASSPHRASE" \
        --output test_credentials.tar test_credentials.tar.gpg
        tar xvf test_credentials.tar
      env:
        SECRET_PASSPHRASE: ${{ secrets.SECRET_PASSPHRASE }}
    - run: npm ci
      name: npm CI
    - run: npm run build --if-present
      name: Build
    - run: npm test
      name: Test
    - uses: actions/upload-artifact@v2
      name: Upload coverage-summary.json
      with:
          name: coverage
          path: coverage/
  
  uploadResult:
      needs: build
      name: Upload Coverage-Result
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v2
        name: Checkout
        
      - uses: actions/download-artifact@v2
        name: Download coverage-summary.json
        with:
          name: coverage

      - name: Upload data
        run: chmod +x .github/scripts/rest_connect.sh; sh .github/scripts/rest_connect.sh
        env:
          USER: ${{ secrets.REST_USER }}
          PASSWORD: ${{ secrets.REST_PASSWORD }}
