# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Test

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [15.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    name: Build and Test

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup Node.js
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Decrypt secrets
      run: |
        cd secrets;
        gpg --quiet --batch --yes --decrypt --passphrase="$SECRET_PASSPHRASE" \
        --output firebaseConfig.tar firebaseConfig.tar.gpg
        tar xvf firebaseConfig.tar
        gpg --quiet --batch --yes --decrypt --passphrase="$SECRET_PASSPHRASE" \
        --output firestoreKey.tar firestoreKey.tar.gpg
        tar xvf firestoreKey.tar
        gpg --quiet --batch --yes --decrypt --passphrase="$SECRET_PASSPHRASE" \
        --output jwtSecret.tar jwtSecret.tar.gpg
        tar xvf jwtSecret.tar
      env:
        SECRET_PASSPHRASE: ${{ secrets.SECRET_PASSPHRASE }}
    - run: npm ci
      name: npm CI
    - run: npm run build --if-present
      name: Build
    - run: npm test
      name: Test
