name: Deploy
 
on:
  push:
    branches:
     - main
 
jobs:

  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version:
          - 16
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    name: Build and test

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup Node.js
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Decrypt secrets
      run: |
        cd secrets;
        gpg --quiet --batch --yes --decrypt --passphrase="$SECRET_PASSPHRASE" \
        --output firebase_config.tar firebase_config.tar.gpg
        tar xvf firebase_config.tar
        gpg --quiet --batch --yes --decrypt --passphrase="$SECRET_PASSPHRASE" \
        --output firestore_key.tar firestore_key.tar.gpg
        tar xvf firestore_key.tar
        gpg --quiet --batch --yes --decrypt --passphrase="$SECRET_PASSPHRASE" \
        --output secret_key.tar secret_key.tar.gpg
        tar xvf secret_key.tar
        gpg --quiet --batch --yes --decrypt --passphrase="$SECRET_PASSPHRASE" \
        --output test_credentials.tar test_credentials.tar.gpg
        tar xvf test_credentials.tar
      env:
        SECRET_PASSPHRASE: ${{ secrets.SECRET_PASSPHRASE }}
    - run: npm ci
      name: Install via npm CI
    - run: npm run build --if-present
      name: Build
    - run: npm test;
      name: Test
 
  deploy:
  
    runs-on: ubuntu-latest
    
    name: Deploy
    
    needs: build
    
    steps:
      - name: Deploy rest-shield
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: ${{ secrets.HOST_ADDRESS }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
          script: |
            cd /opt/hosted-services/rest-shield/
            git fetch --all
            git reset --hard origin/main
            npm clean-install
            pm2 restart /opt/hosted-services/rest-shield/server.ts --name rest-shield
